# Site settings
title: JACK WU
email: xuwupeng2000@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It is a question not an answer...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: xuwupeng2000
github_username:  xuwupeng2000

# Build settings
markdown: kramdown
